name: Mirror Repository

on:
  push:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Configure Git
      run: |
        git config --global user.name "Mirror Bot"
        git config --global user.email "mirror-bot@example.com"
    
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GIT_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    
    - name: Add remote mirror
      run: |
        git remote add mirror ${{ secrets.MIRROR_REPO_URL }}
    
    - name: Push all branches excluding .github
      run: |
        for branch in $(git for-each-ref --format='%(refname:short)' refs/heads/); do
          echo "Processing branch: $branch"
          git checkout -b mirror-$branch $branch
          git rm -r --cached .github || true
          git commit -m "Remove .github for mirror" || true
          git push mirror mirror-$branch:$branch --force
          git checkout $branch
          git branch -D mirror-$branch
        done
    
    - name: Push all tags
      run: |
        git push mirror --tags --force
    
    - name: Verify mirror
      run: |
        echo "Mirroring completed successfully"
        echo "Source: ${{ github.repository }}"
        echo "Target: ${{ secrets.MIRROR_REPO_URL }}"
