name: Mirror Repository

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  test:
    name: Run Unit Tests (GTest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install vcpkg
        run: git clone https://github.com/microsoft/vcpkg && ./vcpkg/bootstrap-vcpkg.sh

      - name: Install GTest
        run: ./vcpkg install gtest

      - name: Configure CMake
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ./build/tests --gtest_output=xml:test-results.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results.xml

  mirror:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "Mirror Bot"
          git config --global user.email "mirror-bot@example.com"

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GIT_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Add remote mirror
        run: git remote add mirror ${{ secrets.MIRROR_REPO_URL }}

      - name: Push to mirror
        run: |
          git push mirror --all --force
          git push mirror --tags --force

      - name: Verify mirror
        run: |
          echo "Mirroring completed successfully"
          echo "Source: ${{ github.repository }}"
          echo "Target: ${{ secrets.MIRROR_REPO_URL }}"
